### ISSUE TITLE
Ownership of the status endpoint and third party status list providers use case

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/draft-ietf-oauth-status-list#10]
we assume (and that's good) that the issuer of a VC is responsible of its lifecycle, and then it has to maintain the revocation status of its issued vcs.

there may be some cases where the revocation list could be deployed outside the issuer domain

in this case the status JSON Object shouln't be a JWS instead, signed by the owner of the status list (different from the isser)? 

````
  "sts": $JWS
````

**Comment by tplooker** [comment]
@peppelinux 3rd party distribution of the status list (e.g it being hosted by someone other than the issuer) I think is a good usecase to elaborate on, however regardless of host I think it is important that the list is always signed by the issuer.

**Comment by peppelinux** [comment]
I prefer a decentralized approach, where each issuer manages the lifecycle of its issuance but there comes other models where revocation must or may be hosted to third parties 

so we should give a verifiable attestation of the status provider, and this attestation must be verifiable

this brings again the aspect to have this status object directly as a JWS for both cases but I'd prefer a plantext json is the issuer is the same, just because it is simple and the hope that there won't be centralized approaches

differently, if the issuer is not the same and the status object should be a JWS, well in it we should have a verifiable trust (x5c, trust_chain ...) embedded or referenced in it -> payload increase but necessary

**Comment by tplooker** [comment]
@peppelinux so If I understand you correctly you would like to support a model where the statuse being conveyed about a JWT is by someone other than the issuer of the JWT?

**Comment by peppelinux** [comment]
I dont like It but there May be some cases when It Is required

Not in my implementations :-)

**Comment by paulbastian** [comment]
I have this use case also in mind, I parked this concept in the privacy considerations part 5.5 as hosting service. It's an easy way to get additional privacy because the issuer can not track who accessed the status list

**Comment by paulbastian** [comment]
Clarify after discussions with @tplooker : This is only about hosting the Status List Token, not about the htird party signing the Token

**Comment by paulbastian** [comment]
Editors Call:
- we acknowledge 3rd Party hosting by the Status List Provider and will explain this in more detail in the spec, see #158 
- other scenarios, where the issuer of the Referenced Token is not the same as the issuer of the Status List Token will not be detailed, but are still possible to do with this spec given that we don't give guidance on the key management

Pending close if no new feedback

**Comment by paulbastian** [comment]
Editors Call:
- opened #159 to solve the latter discussion
- closing this one
