### ISSUE TITLE
do we mandate the issuer of Referenced Token is the same entity issuing the Status List?

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#108]

**Comment by MattiasLass** [comment]
I was about to create a separate related issue, but perhaps this is more suitable as a comment here...

As-is I do not understand what is being achieved by requiring the `iss` to be equal in both the Referenced Token and the Status List Token. Yes, the requirement has the disclaimer that it only applies _in the absence of an application profile specifying otherwise_, but still, it creates confusion.

Perhaps the original intent was to use this claim as a sort of rudimentary integrity check - to validate that the Status List Token has been issued by a trusted party (namely the same party that issued the Referenced Token). If so, it feels out of scope of this specification given that the Design Consideration section states: 'the specification shall not specify key resolution or trust frameworks'. 

It seems to me that `iss` claim cannot be meaningfully used without specifying more regarding the trust framework and perhaps it should not be included in this specification at all.
