### ISSUE TITLE
Status List Endpoint is undefined

### ISSUE THREAD

**Issue by joelposti** [oauth-wg/draft-ietf-oauth-status-list#120]
Section [8.1. ](https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-02.html#section-8.1)[Status List Request](https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-02.html#name-status-list-request) mentions Status List Endpoint. The term is not mentioned elsewhere in the specification nor is it defined.

**Comment by paulbastian** [comment]
Thanks for the feedback.

Discussion Editors Call:
- connected to the discussion whether Status List Provider is an entity that shall be described in the spec
- intend to clarify the term for next iteration
