### ISSUE TITLE
Ambiguous/contradictory language in the `sub` (subject) claim description

### ISSUE THREAD

**Issue by MattiasLass** [oauth-wg/draft-ietf-oauth-status-list#125]
> `sub`: REQUIRED. The `sub` (subject) claim MUST specify a unique string identifier for the Status List Token. The value MUST be equal to that of the `uri` claim contained in the `status_list` claim of the Referenced Token.

The first and second sentence of this description seem contradictory to me. The first sentence seems to state that (all?) Status List Tokens should have a unique identifier included as their `sub` claim. The second sentence directly contradicts this uniqueness requirement. Perhaps I'm misunderstanding what is meant by 'uniqueness' in the first sentence, but in that case the language is quite ambiguous.

As the `sub` claim seems to have been added solely for including the `uri` from the Referenced Token in the Status List Token (as described in #28), perhaps the sentences should simply be reworded to not mention uniqueness. So something like:

-  `sub`: REQUIRED. The `sub` (subject) claim MUST be equal to the `uri` claim contained in the `status_list` claim of the Referenced Token.

**Comment by paulbastian** [comment]
The `sub` is basically the URI by which the Status List Token is retrieved. As Status List Tokens may be downloaded for offline use, further re-transmission or archiving, its important to also store the URI in the Token, such that it can be compared by others to the `uri` of the `status_list` claim of the Referenced Token.

I see that the text may be confusing, it should be clearer as "URI" may be better than "unique string identifier" and URI is unique anyway.

How about:

`sub`: REQUIRED. The `sub` (subject) claim MUST specify the URI of the Status List Token. The value MUST be equal to that of the `uri` claim contained in the `status_list` claim of the Referenced Token.

**Comment by MattiasLass** [comment]
Yes thank you, this wording clears it up.

If you wanted to be very precise instead of `URI of the Status List Token` you could write `URI of the Status List Endpoint used to obtain the Status List Token`. But perhaps my suggestion is too verbose, what you've written gets the idea across.
