### ISSUE TITLE
Remove the requirement to use TLS to retrieve Status List Tokens from the Status List Endpoint

### ISSUE THREAD

**Issue by MattiasLass** [oauth-wg/draft-ietf-oauth-status-list#126]
Section '8.1. Status List Request' currently states:

> Communication with the Status List Endpoint MUST utilize TLS.

This seems redundant when the endpoint is used to retrieve a Status List Token, as the Token's integrity is already guaranteed by requiring it to be signed using an asymmetric cryptographic algorithm.

If requiring TLS was intended for providing confidentiality of the Token, this seems unnecessary. The endpoint is publicly accessible - there does not seem to be any client authentication mechanisms described for it - thus the Tokens could be retrieved by anybody.

**Comment by paulbastian** [comment]
Hi @MattiasLass , thanks for the feedback!

I think you are correct that we could relax using TLS when a Status List Token is queried. However, if an unsigned Status List is returned, we need TLS as an integrity mechanism.

**Comment by MattiasLass** [comment]
> if an unsigned Status List is returned, we need TLS as an integrity mechanism

Yes I vehemently agree :)

Btw, perhaps the issue is a bit broader that just permitting plain HTTP when obtaining Status List Tokens. I don't think it's currently explicitly stated in the specification whether a Status List Provider should/must simultaneously provide both plain Status Lists and Status List Tokens. Ie the standard states that an RP should use the Accept-Header to indicate the requested response type, but it does not specify what the Status List Provider should do if it is unable to provide the requested response type.

I think this is somewhat relevant under this issue as:
- if you were to simply add a sentence to the spec permitting plain HTTP for Status List Tokens
- then an Issuer would have to decide whether to put an HTTP or HTTPS URI in the `status` claim of the Referenced Token
- but this somewhat contradicts with the Accept-Header mechanism which would seem to indicate (to the reader of the spec) that it's up to the RP to choose the response type.

Perhaps the Issuer should explicitly specify supported response type(s) in the `status` claim of the Referenced Token? Ie there could be an additional attribute in the `status_list` object under the `status` claim specifying the supported formats. Such an attribute could prove beneficial in other regards as well. For example, I don't immediately see an use case where an Issuer/Status List Provider would be providing cbor/cwt Status Lists for JOSE Referenced Tokens.
