### ISSUE TITLE
Add Security Consideration on signing status list

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/draft-ietf-oauth-status-list#128]
It may be a good idea to add guidance on the implications of not signing the status list to make the security trade-offs explicit.

**Comment by c2bo** [comment]
Thanks for opening the issue and I agree, we should probably be a lot more explicit for this part.
Biggest question would be where this fits? Perhaps a general introduction at the start of section 5?

**Comment by paulbastian** [comment]
Editors Call Discussion:
- Add security consideration for now
- Discuss if the unsigned option should stay in or not for the long term (usefulness/security/less options)

**Comment by paulbastian** [comment]
Linked to #147

**Comment by paulbastian** [comment]
Editors Call:
- IETF decision to drop unsigned option
- therefore, this issue will be resolved, as Status List Token will always be signed
