### ISSUE TITLE
Fix links to Github repo in About this document

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#136]

**Comment by cre8** [comment]
@c2bo right now `https://github.com/vcstuff/draft-ietf-oauth-status-list` is referenced, but `https://github.com/oauth-wg/draft-ietf-oauth-status-list/` is the correct one.

Since github is redirecting by itself, this is not a critical bug

**Comment by c2bo** [comment]
Are you looking at the datatracker or at the latest draft (https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html)?

**Comment by c2bo** [comment]
This was fixed in the current editors draft (after moving to the new gh org) -> imho this can be closed?

**Comment by paulbastian** [comment]
you are correct
