### ISSUE TITLE
Set content type to optional than must

### ISSUE THREAD

**Issue by cre8** [oauth-wg/draft-ietf-oauth-status-list#137]
Some CDNs like github repos/pages only provide static hosting and therefore no way to set the content-type to another value.

For the JOSE case I could publish a txt or json file.
So when it's a json file, it should be equal to `application/statuslist+json`, in case of a JWT it is `application/statuslist+jwt`.

**Comment by paulbastian** [comment]
Editors Call:
- there was an IETF decision to enforce Content-Type
- will be solved by #183
