### ISSUE TITLE
Support an optional feature for historical resolution

### ISSUE THREAD

**Issue by decentralgabe** [oauth-wg/draft-ietf-oauth-status-list#138]
We have a use case, in the financial field, to determine the time when the status of a given credential has changed. This requirement comes from US financial compliance regulation and is non negotiable.

The spec already supports an optional TTL which helps, but does not directly solve this issue. With a validity window (TTL), and consistent fetching (at the windows expiry) of status lists one could determine that a bit had flipped within a given window, and be able to approximate a timestamp of a given status change. Of course, this approach is noisy and inefficient.

To build off this section -- https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#name-history -- we can make this type of query simpler. I would like to see language added to the spec that speaks to the (optional) capability of a status list server to support historical queries, or revisions of the document from a given time period. I believe this would maintain the privacy preserving characteristics of the specification while adding the ability for verifiers to approximate status change time, which is useful in a number of circumstances, especially as an optional-to-implement feature.

I am also open to other solutions that are similarly privacy preserving that support either directly or indirectly discerning 'time of status change', to date I have only seen solutions that would be far less privacy preserving, such as requesting specific instances (losing herd privacy).

**Comment by paulbastian** [comment]
I'm supportive of the idea in general. I imagine an optional feature that would add a specific point of time to the HTTP GET query asking the Status List Provider to return a historic Status List Token. 

I see two scenarios for a RP/Verifier: 
- RP wants to know status at a given point of time, then this would fit very easy
- RP wants to know the point of time of a status change but has no good indicators, then this is quite inefficient

I imagine most usecase would be the first scenario, so that would be fine?

**Comment by decentralgabe** [comment]
1 is a good fit - yes
2 is inefficient, but at least the capability will exist

> we are working on an alternative mechanism that would fit better for this requirement imho

could you provide additional detail?

**Comment by paulbastian** [comment]
Editors Call:
- we gave this another thought whether to integrate this
- extension to HTTP request protocol seems rather simple:
  - HTTP GET https://example.com/statuslist/1?time=1686920170
  - add OPTIONAL query parameter `time` with Unix timestamp in seconds
  - if Status List Provider doesn't support this ignore or throw error?
  - add privacy consideration  that this makes profiling easier

**Comment by paulbastian** [comment]
@decentralgabe we have a PR for this issue, do you want to review #178 ?
