### ISSUE TITLE
OP Metadata Claim for Status List JWT endpoint

### ISSUE THREAD

**Issue by nynymike** [oauth-wg/draft-ietf-oauth-status-list#143]
If an OP wanted to publish the Token Status List JWT on an endpoint, perhaps something like `token_status_list_jwt` with `Content-Type: application/jwt` ... it would be nice to specify that in the spec.

**Comment by paulbastian** [comment]
I'm not sure what you are suggesting. Are you suggesting that AS or RS has a link to a status list token in his metadata or are you suggesting media types?

**Comment by paulbastian** [comment]
Is this covered by #141 ?

**Comment by paulbastian** [comment]
Editors Call:
- add [OAuth (AS) metadata](https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#authorization-server-metadata) that may link then to the Aggreation

**Comment by paulbastian** [comment]
@nynymike does the PR reflect your idea?
