### ISSUE TITLE
Easy way to debug a Status List

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#157]
With this online tool you are quickly able to decode a JWT Status List for debugging:

https://gchq.github.io/CyberChef/#recipe=JWT_Decode()JPath_expression('status_list.lst','%5C%5Cn')From_Base64('A-Za-z0-9-_',true,false)Zlib_Inflate(0,0,'Adaptive',false,false)To_Binary('Line%20feed',8)Add_line_numbers()

Shall we add it to the readme?

**Comment by c2bo** [comment]
I think that is a good idea for the Readme
