### ISSUE TITLE
Clean up IANA section

### ISSUE THREAD

**Issue by c2bo** [oauth-wg/draft-ietf-oauth-status-list#174]
We should clean up the IANA section a bit, especially https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#name-media-type-registration needs some work imho. Can we remove the n/a parameters from that part or are they required?

**Comment by paulbastian** [comment]
I think it is the recommended way: https://datatracker.ietf.org/doc/html/rfc6838#section-5.6

**Comment by paulbastian** [comment]
Closes #175
