### ISSUE TITLE
Revocation and suspension are not that complicated and there are easy tradeoffs

### ISSUE THREAD

**Issue by Denisthemalice** [oauth-wg/draft-ietf-oauth-status-list#209]
In #207, Paul wrote:

> Revocation is complicated and there are no easy tradeoffs, we shouldn't let the reader believe this.

What you write was true before smart phones existed, but the existence of smart phones offers new possibilities. 
If / when trusted apps. can be used on a smart phone, then other status methods become possible.

**Revocation and suspension of digital credentials**

When a Holder is requesting a digital credential, it needs to know the url of the Issuer, while the Issuer needs to know the characteristics of the Holder, e.g., using attestations. This allows to establish a secure channel between them. That channel can then be used to support a "status protocol" between a Holder and an Issuer.

It is important to notice that this alternative method can support both SUSPENSION and revocation. 
As soon as either a suspension or a revocation is decided by the Issuer, it can be taken into account either very quickly by the app. if the smartphone is connected to the Internet, e.g. within five minutes when the app. polls each Issuer every five minutes, or within 24 hours, if the smartphone is not connected to the Internet.

In addition, this alternative method natively supports the issuer-verifier unlinkability characteristic. 

In terms of energy saving, it is "green", since no data centre needs to be used, e.g., to make available large numbers of Token Status Lists.

Up to now, I didn't proposed a name to identify this alternative method. I propose: **status_protocol**

   *  Status Method Value: status_protocol

   *  Status Method Description: A protocol between a Holder and an Issuer where the Issuer instructs the Holder to revoke, 
      suspend or reactivate one or more tokens.

To close the loop, the **status_protocol** method can be considered to be an easy tradeoff. 

:-)

More seriously, it shifts the problem into two other areas: 
-	the downloading of wallet applications into smart phones by trusted wallets providers, and
-	the development of a status protocol between an Holder and an Issuer. 
        In that case, the status protocol could be defined in a standard track RFC.

R**evocation and suspension at once of all the digital credentials contained in a lost or stolen digital identity wallet**

A similar approach can be used to address the case where the Holder is lost or stolen (in practice, when the smart phone is lost or stolen). Instead of placing the burden on the user to contact individually each Issuer that issued a digital credential, it is easier for the user to use a single point of contact: the Holder Provider (i.e., the app. provider).

An app. on a smart phone, already regularly connects to its provider, e.g., to check for software updates. 
An additional protocol to revoke, suspend or reactivate all the digital credentials / tokens hosted by the Holder would be added.

**Comment by c2bo** [comment]
Your proposal relies on the assumption that the application on the wallet can be considered trusted. That is a pretty strong assumption and also different from the assumptions that status list is built upon. If those are your assumptions, it also begs the question, why you would have anything like tokens / credentials anyway if you completely trust the integrity of the data on the smartphone - it could just be unsigned data in that case.

That being said, what you describe is a very different approach and imho does not align with the overall assumptions/concepts of status list. We opened the door for other status mechanism (and I am sure there will be more than 1 in the long run) by creating the extension point with the "status" claim in this specification.

**Comment by paulbastian** [comment]
Revocation has tradeoffs and I agree with Christian. Here are a few points that you did not seem to consider:
- trusting the wallet/holder/smartphone is a difficult assumption and as Christian points out, your model doesn't seem to fit very well with Verifiable Credentials (or saying Referenced Tokens in the context of status mechanisms). Similar things have been done with EAC protocol in the German eID Card, which did not feature issuance and bringing this to the smartphone world revealed some significant challenges with the Secure Elements, which was part of the problem smart-eID project was discontinued. TEEs on today's smartphones are not open to deploying your own trusted applets either.
- you put significant burdens in terms of scalability on issuers and holders, as all issuers need daily communication with all holders, which is much more traffic compared to status list. Also this puts significant availability requirements to all issuers.
- your latter approach is actually more reasonable and similar things are being considered in eIDAS already under the term Wallet Instance Attestation.

I appreciate your comment and we welcome new status mechanisms, that's why we introduced the extension point. However, I think this is the wrong place, as this draft will only introduce the status registry and the extension point and the status list as the very first mechanism. I think you should either start your own draft or discuss this on OAuth/Spice mailing list.

Pending close.

**Comment by Denisthemalice** [comment]
@ Paul: I dislike to sustain conversations during a week-end, but since you indicated "Pending close", I will respond . 
If you have a further reply, please wait until Monday to post it.

@ Christian wrote:

> Your proposal relies on the **assumption** that the application on the wallet **can be considered** trusted. 

Not exactly. My proposal relies on the **requirement** that the application on the wallet **shall be** trusted.

Let us use two worse case examples to illustrate this: 

- if the private key is not well protected within the smart phone, it can be transferred to someone else (with or without the agreement of the legitimate possessor of the associated digital credential) and then after used by another individual.
- if the private key can be used by any application that the individual can download into his smart phone, then this private key can be used remotely by someone else (as long as both smart phones communicate). 
 
In practice, a TEE shall be used.

Let us now make a parallel:

1. When using qualified electronic signatures, before issuing a certificate, the certificate issuer needs to verify that the certificate request originates from a SSCD (Secure Signature Creation Device).

2. In the same way, when using digital credentials, before issuing a digital credential, the issuer needs to verify that the digital credential request originates from a trusted application that supports specific characteristics.

The status_protocol method relies on the fact that the Holder (application) cannot be any kind of application, but that it shall be a trusted application supporting specific characteristics that are necessary for security reasons. However, it adds another functionality to the set of trusted characteristics / functionalities that are already needed.

This means that the status_protocol method can only be supported in the context of a secure implementation.

> That is a pretty strong assumption and also different from the assumptions that status list is built upon.

Yes, it is a different approach, but this approach only takes into account the fact that a Holder supporting both selective disclosure and the verifier-verifier unlinkability property cannot be any kind of application.

> If those are your assumptions, it also begs the question, why you would have anything like tokens / credentials anyway if you completely trust the integrity of the data on the smartphone - it could just be unsigned data in that case.

No. See my earlier responses above. This is wider than simply **trusting the integrity of the data on the smartphone**. 

> That being said, what you describe is a very different approach and imho does not align with the overall assumptions/concepts of status list. 

Yes, it is a different approach which uses a different method.

> We opened the door for other status mechanism (and I am sure there will be more than 1 in the long run) by creating the extension point with the "status" claim in this specification.

This is fine and really appreciated.

Well, at the moment there exist CRLs, OCSP responses and Token Status Lists. These methods pull status information from trusted sources. The status_protocol method pulls status information directly from the Issuer, but contrary to the previously three methods, the pulled information is NEVER made available to the public.

The Holder connects to the Issuer using a key that has been negotiated at the time the digital credential has been requested.
That key allows to establish a secure channel between a Holder and an Issuer. The status query will only be accepted if it comes through the appropriate secure channel.

The status_protocol method relies on the assumption that the Holder is capable from time to time to contact one or more Issuers. So, there is indeed an assumption, but it is a different from the assumption you made at the beginning of your response.

**Comment by Denisthemalice** [comment]
@ Paul:

This draft is only one part of a large puzzle that may be called a Framework or an Architecture and without a global view of this puzzle, it is difficult to identify the additional pieces of the puzzle that are needed.

There is no free lunch and they are two difficulties. Defining a status protocol between a Holder and an Issuer would not be that difficult. A major difficulty is the one you indicate below:

You wrote:

> Here are a few points that you did not seem to consider:

> 

> ·	trusting the wallet/holder/smartphone is a difficult assumption and as Christian points out, your model doesn't seem to fit very well with Verifiable Credentials (or saying Referenced Tokens in the context of status mechanisms). Similar things have been done with EAC protocol in the German eID Card, which did not feature issuance and bringing this to the smartphone world revealed some significant challenges with the Secure Elements, which was part of the problem smart-eID project was discontinued. **_TEEs on today's smartphones are not open to deploying your own trusted applets either._**

Your are last sentence is absolutely true.

There is a need to be able to download in the TEE (Trusted Execution Environment) of a smartphone one or more TAs that are **not** provided by the smartphone manufacturer or the device manager. The hardware is already there, the concepts and the architecture are already there as well, however the software to download from different trusted repositories (and then execute) multiple TAs in a TEE is not yet available.

In the Android environment, when using Trusty, currently multiple TAs cannot (yet) be downloaded into the TEE:

> "Currently all Trusty applications are developed by a single party and packaged with the Trusty kernel image. The entire image is signed and verified by the bootloader during boot. Third-party application development is not supported in Trusty at this time."

**Source**: https://source.android.com/docs/security/features/trusty?hl=en#third-party_trusty_applications

RFC 9397, which is an Informational RFC, describes a Trusted Execution Environment Provisioning (TEEP) Architecture. 
I don't know when / if Trusty will be extended to support some of the concepts described in this RFC.

If the specification and the development of the status_protocol method are done in parallel to the development of a TAM (Trusted Application Manager), the two developments might possibly end-up within the same time frame.

You wrote:

> ·	you put significant burdens in terms of scalability on issuers and holders, as all issuers need daily communication with all holders, which is much more traffic compared to status list. Also this puts significant availability requirements to all issuers.

Well, the size of the messages that will need to be exchanged will be very small. There will be at least two orders of magnitude difference for the traffic between the two methods. Issuers only need to be online once a day. No response from an Issuer does not block the system: it only delays the moment when the suspension or the revocation will be enforced by the Holder. This is much better than the case when a Status Issuer is not available online: it blocks the system.

You wrote:

> ·	your latter approach is actually more reasonable and similar things are being considered in eIDAS already under the term Wallet Instance Attestation.


I have not seen "similar things are being considered in eIDAS already under the term Wallet Instance Attestation". 
Would you have a pointer ?

**MY OWN CONCLUSION**

At the moment, it might be quite hard for a reader to think that another status method can be used and that this method is capable to support functionality that is not supported by the status_list method: suspension can be supported while the Issuer-Verifier unlinkability is natively supported.

I have provided a detailed description of this method by raising two issues. The goal was not to place this detailed description in the core of this document, but only to make it understandable.

I propose that the draft should indicate in clause 12.5 (Unlinkability) that another method, based on a different principle, can be used, supporting additional functionality and to include a one page informative annex that gives a flavour of it.

If you agree in principle, I let you add in the core of the document a few sentences, to explain this and then I can provide the one page explanation.

**One additional comment:**

Along this discussion, another topic has emerged: in case of the loss or the theft of the smartphone, the ability to revoke or suspend the Holder as a whole instead of revoking or suspending the digital credentials [Tokens] one by one by every Issuer.
I believe that this should be mentioned "somewhere" in the draft.

You finally wrote:

> I think you should either start your own draft or discuss this on OAuth/Spice mailing list.

The question is whether some WG members would be interested to participate to this effort, but the timing is not well chosen and I will wait until next year before initiating a discussion on this topic on the mailing lists.

**Comment by paulbastian** [comment]
As you point out that using TEEs in the way you envision is currently not possible, I think its fair to say that tradeoffs have to be made in revocation. At least I'm only considering methods that are actually doable with today's technology and how it is deployed.

Beside that I merged the suggestions you had and clarified that jother status mechnaisms have different tradeoffs and security and privacy consideration. I would refrain from adding text on the potential mechanisms, as I haven't seen this in other RFCs and naming a single one would be descriminating to other status ideas.
