### ISSUE TITLE
Mixing JSON and CBOR formats

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#38]
Is it allowed/recommended to have Status List Token in one format and the Referenced Token in another format?

**Comment by c2bo** [comment]
Imho, I would not prevent this from this draft, but most likely people will keep within their ecosystem.

**Comment by paulbastian** [comment]
Editors Call:
- keep the option to have the mixing
- add some guidance to implementers consideration
