### ISSUE TITLE
Rename claim names of Referenced Token

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#40]
@tlodderstedt propoeses to:

- rename `status` to something shorter
- rename `uri` to `slt` (status list token)

**Comment by c2bo** [comment]
I like the idea to rename `uri` to  `slt`. That makes it even clearer what to expect and we could still require `slt` to be an URI.

**Comment by paulbastian** [comment]
Status List Token:
```
{
  "typ": "statuslist+jwt",
  "alg": "ES256",
  "kid": "11"
}
.
{
  "iss": "https://example.com",
  "sub": "https://example.com/statuslists/1",
  "iat": 1683560915,
  "exp": 1686232115,
  "sl": {
    "bts": 1,
    "lst": "H4sIAMo_jGQC_9u5GABc9QE7AgAAAA"
  }
}
```
sl (tatus list), bts (bits), lst (list)
Referenced Token:
```
{
  "alg": "ES256",
  "kid": "11"
}
.
{
  "iss": "https://example.com",
  "sta": {
    "slt": "https://example.com/statuslists/1",
    "idx": 0    
  }
}
```
sta (status), slt(status list toklen), idx (index)

**Comment by paulbastian** [comment]
Editors Call:
- Given that this would be breaking changes and we have a considerable amount of specifications and having limited benefits on the other side, we tend to not make these changes
