### ISSUE TITLE
Strip = from Base64url encoding?

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#44]

**Comment by paulbastian** [comment]
the text is existing in JWT encoding, does it make sense to emphasize this change from standard base64url encoding again in our spec?

**Comment by c2bo** [comment]
I like the solution in sd-jwt - they introduced it as terminology:
> base64url denotes the URL-safe base64 encoding without padding defined in Section 2 of [[RFC7515](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html#RFC7515)].

Should we move that to terminology and reference via base64url in the text?
