### ISSUE TITLE
Mandatory signature algorithms?

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#46]
Do we want normative text on required signature algorithms, e.g. ES256?

**Comment by c2bo** [comment]
Imho, this should be part of an interop profile and not part of this spec. Imho, we should stick to / allow jose/cose in this work.

**Comment by paulbastian** [comment]
Editors Call:
- agreed to close this
- JOSE already has mandatory ones
- mandatory algos didn't seem to age will in the past
- leave it to profiles
