### ISSUE TITLE
"A Status List can not represent multiple statuses per Referenced Token"

### ISSUE THREAD

**Issue by mprorock** [oauth-wg/draft-ietf-oauth-status-list#51]
There are multiple cases that require multiple statuses to be attached to something.... this draft is also covering cbor

can we at least for cbor permit a flag that lets us embed an array of bytes into a particular status index - that would permit this use case to be covered easily

**Comment by paulbastian** [comment]
Multiple statuses are reflected by having more than 1 bit per index (through bits 2,4 or 8).
Beside this, the option to have multiple Status Lists per Referenced Token still persists, however this is probably not a major use case.
Adding the option for arrays in the Status List seems too complicated as we already have multiple bits as an option

**Comment by paulbastian** [comment]
Editors Call:
- the design considerations aim for simplicity for the majority of use cases
- the requirement seems niche to us and complicates the design, while we already have the ability to reflect more than 0/1 with `bits` > 1
- given that we have the extension point at the `status` claim, one could build an extended status list that allows for such feature
- however, we would like to understand these use cases better

**Comment by paulbastian** [comment]
Editors Call:
- pending close without further feedback
