### ISSUE TITLE
restriction to numeric status

### ISSUE THREAD

**Issue by mprorock** [oauth-wg/draft-ietf-oauth-status-list#53]
"Status Types MUST be numeric values between 0 and 255" 
Probably better to just have hex pass through if you are after numerics, rather than set a status type, otherwise, why would we not permit a message to be attached and referenced, perhaps from a lookup table external.  see the `credentialSubject.statusMessages` implementation/spec [defined in the equivalent w3c work](https://w3c.github.io/vc-status-list-2021/#statuslist2021credential)

**Comment by paulbastian** [comment]
Editors Call:
- we need further information to understand this issue
- Status Types are represented as a number with 1 to 8 bits according to the chosen `bits` value
- hex is just the representation, but the actual usage in this draft is binary
- we favor few, simple status types described in a global registry to avoid misunderstandings
- in this registry there may be some "application-specific" types, where ecosystems could define this on their own, but out of scope for this spec
- pending close without further feedback
