### ISSUE TITLE
Optional authorization towards the statusList endpoint

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/draft-ietf-oauth-status-list#7]
To limit the tracking/profiling possiblities of the statusList, an optional mechanism for verifiers to get authorized access could be implemented. This limits the entities that have access to the status list. A mechanism could be:
- not defined in this spec but added to privacy considerations
- defined in this spec

**Comment by c2bo** [comment]
I think it is a good idea to at least desribe the different scenarios of who (verifier/holder) is requesting the status list and how it is protected.

**Comment by tplooker** [comment]
Agreed, one question this raises for me is whether there needs to be any information in the status entry of the issued credential that convey's this constraint to a verifying party (e.g the status list is access controlled and you need to do X to be able to resolve it?)

**Comment by c2bo** [comment]
Main spec should have a short discussion why/where this would make sense.
In-depth discussion can happen in an appendix.

**Comment by c2bo** [comment]
Discussed in editor's call and decided that this is out of scope currently for the draft
