### ISSUE TITLE
Consider making `status` a JWT header instead of a JWT claim

### ISSUE THREAD

**Issue by awoie** [oauth-wg/draft-ietf-oauth-status-list#86]
`status` is not really a claim about a subject and is never selectively disclosed, so it would makes sense to make it a JWT header. It would also work well with the existing `crit` JOSE header that can then mark `status` as critical.

See https://github.com/oauth-wg/oauth-sd-jwt-vc/issues/192

**Comment by paulbastian** [comment]
I like the idea, but I think we need more input from others

**Comment by peppelinux** [comment]
Using JSON serialization or COSE Sign Document (as mdoc cbor MSO) would give the benefit to allow the update of the status object without breaking the signature of the JWS.

While having a compact-serialization not.

I'd see benefits in having it in the unprotected header, while in the protected header not.

I believe that there may be use cases or situations where the status key may be disclosable, then it makes sense to me to keep it in the payload and allow the issuers to make it disclosable or not.

a least, even if I really don't like this argument, there are some implementations that have issues with custom/unsupported header parameters. This may have huge impact on the implementation -> not a good argument, but something.

definitively, I would like to have the status in the payload, as the credential type and anything in the payload related to the payload.

**Comment by paulbastian** [comment]
Editors Call:
- current approach is in line with current best practice and we wouldn't start the discussion here, see iat, exp..
- would break current implementations without much benefit

**Comment by paulbastian** [comment]
Discussed with @awoie , we are closing this issue.
